// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "./EscrowAuth.sol";
import "../lib/EscrowTypes.sol";
import "../interface/ICrpylioEscrow.sol";

/**
 * @title EscrowOperations
 * @dev Base contract containing core escrow operations
 * @notice All state-changing functions are protected by ReentrancyGuard
 * @custom:security Protected against reentrancy attacks via OpenZeppelin ReentrancyGuard
 */
abstract contract EscrowOperations is ICryplioEscrow, EscrowAuth, ReentrancyGuard, EIP712 {
    using SafeERC20 for IERC20;
    using MessageHashUtils for bytes32;
    
    // Nonce tracking for meta-transactions (seller => nonce => used)
    mapping(address => mapping(uint256 => bool)) public usedNonces;

    // Type hashes for EIP-712
    bytes32 private constant CREATE_ESCROW_TYPEHASH = keccak256(
        "CreateEscrow(bytes32 tradeId,address buyer,address seller,address token,uint256 amount,uint256 expiryTime,uint256 nonce)"
    );

    // Constructor
    constructor(address[] memory _initialTokens) 
        EscrowAuth(_initialTokens) 
        EIP712("CryplioEscrow", "1") 
    {}
    
    /**
     * @dev Internal function to validate escrow creation inputs
     * @param tradeId Trade identifier
     * @param buyer Buyer address
     * @param seller Seller address  
     * @param token Token address
     * @param amount Amount to escrow
     * @param expiryTime Expiry time
     */
    function _validateEscrowInputs(
        bytes32 tradeId,
        address buyer,
        address seller,
        address token,
        uint256 amount,
        uint256 expiryTime
    ) internal view {
        EscrowTypes.validateTradeId(tradeId);
        EscrowTypes.validateAddresses(buyer, seller);
        EscrowTypes.validateAmount(amount);
        EscrowTypes.validateExpiryTime(expiryTime);
        EscrowTypes.validateTokenSupported(supportedTokens[token]);
        EscrowTypes.validateEscrowExists(_escrowExists(tradeId));
    }
    
    /**
     * @notice Emitted when meta-transaction is executed
     * @param seller The signer who authorized the transaction
     * @param nonce The nonce used for this transaction
     * @param relayer The address that paid the gas (platform wallet)
     */
    event MetaTransactionExecuted(address indexed seller, uint256 indexed nonce, address indexed relayer);
    
    /**
     * @notice Create a new escrow for a P2P trade
     * @dev SECURITY: Tokens transferred from seller using safeTransferFrom
     *      ACCESS: Callable by anyone (backend system typically calls this)
     *      REENTRANCY: Protected by nonReentrant modifier
     * @param tradeId Unique identifier for the trade (generated by backend)
     * @param buyer Address receiving tokens after trade completion
     * @param seller Address providing tokens (must approve contract first)
     * @param token ERC20 token address (must be in supportedTokens)
     * @param amount Token amount to lock (must be > 0)
     * @param expiryTime Custom expiry time for this escrow (optional, defaults to 1 hour)
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.UnsupportedToken if token not supported
     * @custom:throws EscrowTypes.EscrowAlreadyExists if tradeId already used
     * @custom:throws EscrowTypes.InvalidExpiryTime if expiryTime out of bounds
     */
    function createEscrow(
        bytes32 tradeId,
        address buyer,
        address seller,
        address token,
        uint256 amount,
        uint256 expiryTime
    ) external virtual override nonReentrant whenNotPaused returns (bool) {
        // Validate inputs
        _validateEscrowInputs(tradeId, buyer, seller, token, amount, expiryTime);
        
        // Only seller can create their own escrow
        if (msg.sender != seller) {
            revert EscrowTypes.Unauthorized();
        }
        
        // Transfer tokens from seller to this contract
        IERC20 tokenContract = IERC20(token);
        tokenContract.safeTransferFrom(seller, address(this), amount);
        
        // Create escrow record
        _createEscrow(tradeId, buyer, seller, token, amount, expiryTime);
        
        emit EscrowTypes.EscrowCreated(tradeId, buyer, seller, token, amount, block.timestamp);
        return true;
    }

    /**
     * @notice Create escrow via meta-transaction (platform wallet pays gas)
     * @dev META-TX: Seller signs message off-chain, platform wallet submits on-chain
     *      SECURITY: Signature verification ensures only seller can authorize their escrow
     *      REENTRANCY: Protected by nonReentrant modifier
     * @param tradeId Unique identifier for the trade
     * @param buyer Address receiving tokens
     * @param seller Address providing tokens (must be the signer)
     * @param token ERC20 token address
     * @param amount Token amount to lock
     * @param expiryTime Custom expiry time
     * @param nonce Unique nonce to prevent replay attacks
     * @param signature EIP-712 signature from seller
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.InvalidSignature if signature is invalid
     * @custom:throws EscrowTypes.NonceAlreadyUsed if nonce was already consumed
     */
    function createEscrowMeta(
        bytes32 tradeId,
        address buyer,
        address seller,
        address token,
        uint256 amount,
        uint256 expiryTime,
        uint256 nonce,
        bytes calldata signature
    ) external nonReentrant whenNotPaused returns (bool) {
        // Validate inputs
        _validateEscrowInputs(tradeId, buyer, seller, token, amount, expiryTime);
        
        // Check nonce not used
        if (usedNonces[seller][nonce]) {
            revert EscrowTypes.NonceAlreadyUsed();
        }
        
        // Build message hash (EIP-712)
        bytes32 structHash = keccak256(abi.encode(
            CREATE_ESCROW_TYPEHASH,
            tradeId,
            buyer,
            seller,
            token,
            amount,
            expiryTime,
            nonce
        ));
        
        bytes32 hash = _hashTypedDataV4(structHash);
        
        // Recover signer from signature
        address signer = ECDSA.recover(hash, signature);
        
        // Verify signer is the seller
        if (signer != seller) {
            revert EscrowTypes.InvalidSignature();
        }
        
        // Mark nonce as used
        usedNonces[seller][nonce] = true;
        
        // Transfer tokens from seller to this contract
        IERC20 tokenContract = IERC20(token);
        tokenContract.safeTransferFrom(seller, address(this), amount);
        
        // Create escrow record
        _createEscrow(tradeId, buyer, seller, token, amount, expiryTime);
        
        emit EscrowTypes.EscrowCreated(tradeId, buyer, seller, token, amount, block.timestamp);
        emit MetaTransactionExecuted(seller, nonce, msg.sender);
        
        return true;
    }

    /**
     * @dev Internal function to transfer tokens with platform fee deduction
     * @param token Token address
     * @param tradeId Trade identifier for event
     * @param recipient Final recipient of tokens (after fee)
     * @param totalAmount Total amount from escrow
     * @param feeBps Fee in basis points (75 = 0.75%, 25 = 0.25%)
     * @return netAmount Amount actually sent to recipient
     */
    function _transferWithFee(
        address token,
        bytes32 tradeId,
        address recipient,
        uint256 totalAmount,
        uint256 feeBps
    ) internal returns (uint256 netAmount) {
        uint256 feeAmount;
        unchecked {
            feeAmount = (totalAmount * feeBps) / 10000;
            netAmount = totalAmount - feeAmount;
        }
        
        // Transfer fee to feeRecipient
        if (feeAmount > 0 && feeRecipient != address(0)) {
            IERC20(token).safeTransfer(feeRecipient, feeAmount);
            emit EscrowTypes.FeeCollected(tradeId, token, feeRecipient, feeAmount, block.timestamp);
        }
        
        // Transfer remaining to recipient
        IERC20(token).safeTransfer(recipient, netAmount);
        
        return netAmount;
    }

    /**
     * @dev Internal function to finalize an escrow (transfer funds and update status)
     * @param escrow Storage reference to the escrow
     * @param tradeId Trade identifier for events
     * @param recipient Final recipient of tokens
     * @param feeBps Fee in basis points
     * @param newStatus New status to set
     * @return netAmount Amount actually sent to recipient
     */
    function _finalizeEscrow(
        EscrowTypes.Escrow storage escrow,
        bytes32 tradeId,
        address recipient,
        uint256 feeBps,
        EscrowTypes.EscrowStatus newStatus
    ) internal returns (uint256 netAmount) {
        // Ensure escrow is still in Locked status
        if (escrow.status != EscrowTypes.EscrowStatus.Locked) {
            revert EscrowTypes.InvalidStatus();
        }

        // Cache storage values to memory to save gas
        address token = escrow.token;
        uint256 amount = escrow.amount;
        
        // Transfer with fee to recipient
        netAmount = _transferWithFee(
            token,
            tradeId,
            recipient,
            amount,
            feeBps
        );
        
        // Update status
        escrow.status = newStatus;
    }

    /**
     * @notice Release escrow funds to buyer after seller confirms fiat payment
     * @dev FINANCIAL: Deducts 0.75% platform fee before transfer
     *      MATH: feeAmount = (amount * FEE_BPS) / 10000, buyerAmount = amount - feeAmount
     *      ACCESS: Only callable by escrow seller
     *      REENTRANCY: Protected by nonReentrant modifier
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.InvalidStatus if escrow not in Locked state
     * @custom:throws EscrowTypes.Unauthorized if caller is not seller
     */
    function releaseEscrow(bytes32 tradeId) 
        external 
        virtual 
        override 
        validEscrow(tradeId) 
        onlySeller(tradeId)
        nonReentrant 
        returns (bool) 
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);
        
        // Finalize escrow and transfer to buyer
        uint256 buyerAmount = _finalizeEscrow(
            escrow,
            tradeId,
            escrow.buyer,
            FEE_BPS,
            EscrowTypes.EscrowStatus.Released
        );
        
        emit EscrowTypes.EscrowReleased(tradeId, escrow.buyer, buyerAmount, block.timestamp);
        return true;
    }

    /**
     * @notice Refund escrow funds to seller (admin only)
     * @dev FINANCIAL: Deducts 0.25% platform fee (lower than release fee to be fair)
     *      MATH: feeAmount = (amount * REFUND_FEE_BPS) / 10000, sellerAmount = amount - feeAmount
     *      ACCESS: Only callable by authorized signers (admin)
     *      REENTRANCY: Protected by nonReentrant modifier
     *      SECURITY: Requires escrow to be refundable (expired or dispute resolved)
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.CannotRefund if escrow not refundable
     * @custom:throws EscrowTypes.Unauthorized if caller not authorized
     * @custom:throws EscrowTypes.InvalidStatus if escrow not in Locked state
     */
    function refundEscrow(bytes32 tradeId)
        external
        virtual
        override
        onlyAuthorized
        validEscrow(tradeId)
        canRefund(tradeId)
        nonReentrant
        returns (bool)
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);
        
        // Finalize escrow and refund to seller
        uint256 sellerAmount = _finalizeEscrow(
            escrow,
            tradeId,
            escrow.seller,
            REFUND_FEE_BPS,
            EscrowTypes.EscrowStatus.Refunded
        );
        
        emit EscrowTypes.EscrowRefunded(tradeId, escrow.seller, sellerAmount, block.timestamp);
        return true;
    }

    /**
     * @notice Force release escrow to buyer by admin (dispute resolution)
     * @dev FINANCIAL: Deducts 0.75% platform fee before transfer
     *      MATH: feeAmount = (amount * FEE_BPS) / 10000, buyerAmount = amount - feeAmount
     *      ACCESS: Only callable by authorized signers (admin)
     *      REENTRANCY: Protected by nonReentrant modifier
     *      SECURITY: Used when backend dispute resolution favors buyer
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.InvalidStatus if escrow not in Locked state
     * @custom:throws EscrowTypes.Unauthorized if caller not authorized
     */
    function forceReleaseEscrow(bytes32 tradeId)
        external
        virtual
        override
        onlyAuthorized
        validEscrow(tradeId)
        nonReentrant
        returns (bool)
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);

        // Finalize escrow and force release to buyer
        uint256 buyerAmount = _finalizeEscrow(
            escrow,
            tradeId,
            escrow.buyer,
            FEE_BPS,
            EscrowTypes.EscrowStatus.Released
        );

        emit EscrowTypes.EscrowForceReleased(tradeId, escrow.buyer, buyerAmount, msg.sender, block.timestamp);
        return true;
    }
}