// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./EscrowAuth.sol";
import "../lib/EscrowTypes.sol";

/**
 * @title EscrowOperations
 * @dev Base contract containing core escrow operations
 * @notice All state-changing functions are protected by ReentrancyGuard
 * @custom:security Protected against reentrancy attacks via OpenZeppelin ReentrancyGuard
 */
abstract contract EscrowOperations is EscrowAuth, ReentrancyGuard {
    using SafeERC20 for IERC20;

    // Events
    /// @notice Emitted when escrow is created and tokens locked
    /// @dev Used for tracking all escrow creation events off-chain
    event EscrowCreated(
        bytes32 indexed tradeId,
        address indexed buyer,
        address indexed seller,
        address token,
        uint256 amount,
        uint256 timestamp
    );
    
    /// @notice Emitted when seller releases funds to buyer after confirming payment
    /// @dev Amount emitted is after fee deduction
    event EscrowReleased(
        bytes32 indexed tradeId,
        address indexed seller,
        uint256 amount,
        uint256 timestamp
    );
    
    /// @notice Emitted when admin refunds escrow to seller
    /// @dev No fee is deducted on refunds - full amount returned
    event EscrowRefunded(
        bytes32 indexed tradeId,
        address indexed buyer,
        uint256 amount,
        uint256 timestamp
    );
    
    /// @notice Emitted when platform fee is collected
    /// @dev Fee = (amount * FEE_BPS) / 10000 where FEE_BPS = 75 (0.75%)
    event FeeCollected(
        bytes32 indexed tradeId,
        address indexed token,
        address feeRecipient,
        uint256 feeAmount,
        uint256 timestamp
    );

    /// @notice Emitted when admin force releases escrow to buyer (dispute resolution)
    /// @dev releasedBy tracks which admin performed the action for audit trail
    event EscrowForceReleased(
        bytes32 indexed tradeId,
        address indexed buyer,
        uint256 amount,
        address indexed releasedBy,
        uint256 timestamp
    );
    

    // Constructor
    constructor(address[] memory _initialTokens) EscrowAuth(_initialTokens) {}
    
    /**
     * @notice Create a new escrow for a P2P trade
     * @dev SECURITY: Tokens transferred from seller using safeTransferFrom
     *      ACCESS: Callable by anyone (backend system typically calls this)
     *      REENTRANCY: Protected by nonReentrant modifier
     * @param tradeId Unique identifier for the trade (generated by backend)
     * @param buyer Address receiving tokens after trade completion
     * @param seller Address providing tokens (must approve contract first)
     * @param token ERC20 token address (must be in supportedTokens)
     * @param amount Token amount to lock (must be > 0)
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.UnsupportedToken if token not supported
     * @custom:throws EscrowTypes.EscrowAlreadyExists if tradeId already used
     */
    function createEscrow(
        bytes32 tradeId,
        address buyer,
        address seller,
        address token,
        uint256 amount
    ) external nonReentrant returns (bool) {
        // Validate inputs
        EscrowTypes.validateTradeId(tradeId);
        EscrowTypes.validateAddresses(buyer, seller);
        EscrowTypes.validateAmount(amount);
        
        // Validate token support
        if (!supportedTokens[token]) {
            revert EscrowTypes.UnsupportedToken();
        }
        
        // Check if escrow already exists
        if (_escrowExists(tradeId)) {
            revert EscrowTypes.EscrowAlreadyExists();
        }
        
        // Transfer tokens from seller to this contract
        IERC20 tokenContract = IERC20(token);
        tokenContract.safeTransferFrom(seller, address(this), amount);
        
        // Create escrow record
        _createEscrow(tradeId, buyer, seller, token, amount);
        
        emit EscrowCreated(tradeId, buyer, seller, token, amount, block.timestamp);
        return true;
    }
    
    /**
     * @notice Release escrow funds to buyer after seller confirms fiat payment
     * @dev FINANCIAL: Deducts 0.75% platform fee before transfer
     *      MATH: feeAmount = (amount * FEE_BPS) / 10000, buyerAmount = amount - feeAmount
     *      ACCESS: Only callable by escrow seller
     *      REENTRANCY: Protected by nonReentrant modifier
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.InvalidStatus if escrow not in Locked state
     * @custom:throws EscrowTypes.Unauthorized if caller is not seller
     */
    function releaseEscrow(bytes32 tradeId) 
        external 
        validEscrow(tradeId) 
        onlySeller(tradeId)
        nonReentrant 
        returns (bool) 
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);
        
        // Allow release if Locked 
        if (escrow.status != EscrowTypes.EscrowStatus.Locked) {
            revert EscrowTypes.InvalidStatus();
        }
        
        // MATH: Fee calculation - (amount * 75) / 10000 = 0.75%
        // Example: 100 USDT * 75 / 10000 = 0.75 USDT fee
        uint256 feeAmount = (escrow.amount * FEE_BPS) / 10000;
        uint256 buyerAmount = escrow.amount - feeAmount;
        
        // Transfer fee to feeRecipient
        if (feeAmount > 0 && feeRecipient != address(0)) {
            IERC20(escrow.token).safeTransfer(feeRecipient, feeAmount);
            emit FeeCollected(tradeId, escrow.token, feeRecipient, feeAmount, block.timestamp);
        }
        
        // Transfer remaining to buyer
        IERC20(escrow.token).safeTransfer(escrow.buyer, buyerAmount);
        
        // Update status
        _updateEscrowStatus(tradeId, EscrowTypes.EscrowStatus.Released);
        
        emit EscrowReleased(tradeId, escrow.buyer, buyerAmount, block.timestamp);
        return true;
    }

    /**
     * @notice Refund escrow funds to seller (admin only)
     * @dev FINANCIAL: Full refund - NO fee deducted on refunds
     *      ACCESS: Only callable by authorized signers (admin)
     *      REENTRANCY: Protected by nonReentrant modifier
     *      SECURITY: Requires escrow to be refundable (expired or dispute resolved)
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.CannotRefund if escrow not refundable
     * @custom:throws EscrowTypes.Unauthorized if caller not authorized
     */
    function refundEscrow(bytes32 tradeId)
        external
        onlyAuthorized
        validEscrow(tradeId)
        canRefund(tradeId)
        nonReentrant
        returns (bool)
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);
        
        // Transfer funds to seller
        IERC20(escrow.token).safeTransfer(escrow.seller, escrow.amount);
        
        // Update status
        _updateEscrowStatus(tradeId, EscrowTypes.EscrowStatus.Refunded);
        
        emit EscrowRefunded(tradeId, escrow.seller, escrow.amount, block.timestamp);
        return true;
    }

    /**
     * @notice Force release escrow to buyer by admin (dispute resolution)
     * @dev FINANCIAL: Deducts 0.75% platform fee before transfer
     *      MATH: feeAmount = (amount * FEE_BPS) / 10000, buyerAmount = amount - feeAmount
     *      ACCESS: Only callable by authorized signers (admin)
     *      REENTRANCY: Protected by nonReentrant modifier
     *      SECURITY: Used when backend dispute resolution favors buyer
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.InvalidStatus if escrow not in Locked state
     * @custom:throws EscrowTypes.Unauthorized if caller not authorized
     */
    function forceReleaseEscrow(bytes32 tradeId)
        external
        onlyAuthorized
        validEscrow(tradeId)
        nonReentrant
        returns (bool)
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);

        // Allow force release only if Locked
        if (escrow.status != EscrowTypes.EscrowStatus.Locked) {
            revert EscrowTypes.InvalidStatus();
        }

        // MATH: Fee calculation - (amount * 75) / 10000 = 0.75%
        // Example: 100 USDT * 75 / 10000 = 0.75 USDT fee
        uint256 feeAmount = (escrow.amount * FEE_BPS) / 10000;
        uint256 buyerAmount = escrow.amount - feeAmount;

        // Transfer fee to feeRecipient
        if (feeAmount > 0 && feeRecipient != address(0)) {
            IERC20(escrow.token).safeTransfer(feeRecipient, feeAmount);
            emit FeeCollected(tradeId, escrow.token, feeRecipient, feeAmount, block.timestamp);
        }

        // Transfer remaining to buyer
        IERC20(escrow.token).safeTransfer(escrow.buyer, buyerAmount);

        // Update status
        _updateEscrowStatus(tradeId, EscrowTypes.EscrowStatus.Released);

        emit EscrowForceReleased(tradeId, escrow.buyer, buyerAmount, msg.sender, block.timestamp);
        return true;
    }
}