// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./EscrowAuth.sol";
import "../lib/EscrowTypes.sol";

/**
 * @title EscrowOperations
 * @dev Base contract containing core escrow operations
 * @notice All state-changing functions are protected by ReentrancyGuard
 * @custom:security Protected against reentrancy attacks via OpenZeppelin ReentrancyGuard
 */
abstract contract EscrowOperations is EscrowAuth, ReentrancyGuard {
    using SafeERC20 for IERC20;
    
    // Constructor
    constructor(address[] memory _initialTokens) EscrowAuth(_initialTokens) {}
    
    /**
     * @notice Create a new escrow for a P2P trade
     * @dev SECURITY: Tokens transferred from seller using safeTransferFrom
     *      ACCESS: Callable by anyone (backend system typically calls this)
     *      REENTRANCY: Protected by nonReentrant modifier
     * @param tradeId Unique identifier for the trade (generated by backend)
     * @param buyer Address receiving tokens after trade completion
     * @param seller Address providing tokens (must approve contract first)
     * @param token ERC20 token address (must be in supportedTokens)
     * @param amount Token amount to lock (must be > 0)
     * @param expiryTime Custom expiry time for this escrow (optional, defaults to 1 hour)
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.UnsupportedToken if token not supported
     * @custom:throws EscrowTypes.EscrowAlreadyExists if tradeId already used
     * @custom:throws EscrowTypes.InvalidExpiryTime if expiryTime out of bounds
     */
    function createEscrow(
        bytes32 tradeId,
        address buyer,
        address seller,
        address token,
        uint256 amount,
        uint256 expiryTime
    ) external nonReentrant returns (bool) {
        // Validate inputs
        EscrowTypes.validateTradeId(tradeId);
        EscrowTypes.validateAddresses(buyer, seller);
        EscrowTypes.validateAmount(amount);
        EscrowTypes.validateExpiryTime(expiryTime);
        
        // Validate token support
        if (!supportedTokens[token]) {
            revert EscrowTypes.UnsupportedToken();
        }
        
        // Check if escrow already exists
        if (_escrowExists(tradeId)) {
            revert EscrowTypes.EscrowAlreadyExists();
        }
        
        // Only seller can create their own escrow
        if (msg.sender != seller) {
            revert EscrowTypes.Unauthorized();
        }
        
        // Transfer tokens from seller to this contract
        IERC20 tokenContract = IERC20(token);
        tokenContract.safeTransferFrom(seller, address(this), amount);
        
        // Create escrow record
        _createEscrow(tradeId, buyer, seller, token, amount, expiryTime);
        
        emit EscrowTypes.EscrowCreated(tradeId, buyer, seller, token, amount, block.timestamp);
        return true;
    }

    /**
     * @notice Release escrow funds to buyer after seller confirms fiat payment
     * @dev FINANCIAL: Deducts 0.75% platform fee before transfer
     *      MATH: feeAmount = (amount * FEE_BPS) / 10000, buyerAmount = amount - feeAmount
     *      ACCESS: Only callable by escrow seller
     *      REENTRANCY: Protected by nonReentrant modifier
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.InvalidStatus if escrow not in Locked state
     * @custom:throws EscrowTypes.Unauthorized if caller is not seller
     */
    function releaseEscrow(bytes32 tradeId) 
        external 
        validEscrow(tradeId) 
        onlySeller(tradeId)
        nonReentrant 
        returns (bool) 
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);
        
        // Allow release if Locked 
        if (escrow.status != EscrowTypes.EscrowStatus.Locked) {
            revert EscrowTypes.InvalidStatus();
        }
        
        // MATH: Fee calculation - (amount * 75) / 10000 = 0.75%
        // Example: 100 USDT * 75 / 10000 = 0.75 USDT fee
        uint256 feeAmount = (escrow.amount * FEE_BPS) / 10000;
        uint256 buyerAmount = escrow.amount - feeAmount;
        
        // Transfer fee to feeRecipient
        if (feeAmount > 0 && feeRecipient != address(0)) {
            IERC20(escrow.token).safeTransfer(feeRecipient, feeAmount);
            emit EscrowTypes.FeeCollected(tradeId, escrow.token, feeRecipient, feeAmount, block.timestamp);
        }
        
        // Transfer remaining to buyer
        IERC20(escrow.token).safeTransfer(escrow.buyer, buyerAmount);
        
        // Update status
        _updateEscrowStatus(tradeId, EscrowTypes.EscrowStatus.Released);
        
        emit EscrowTypes.EscrowReleased(tradeId, escrow.buyer, buyerAmount, block.timestamp);
        return true;
    }

    /**
     * @notice Refund escrow funds to seller (admin only)
     * @dev FINANCIAL: Deducts 0.25% platform fee (lower than release fee to be fair)
     *      MATH: feeAmount = (amount * REFUND_FEE_BPS) / 10000, sellerAmount = amount - feeAmount
     *      ACCESS: Only callable by authorized signers (admin)
     *      REENTRANCY: Protected by nonReentrant modifier
     *      SECURITY: Requires escrow to be refundable (expired or dispute resolved)
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.CannotRefund if escrow not refundable
     * @custom:throws EscrowTypes.Unauthorized if caller not authorized
     * @custom:throws EscrowTypes.InvalidStatus if escrow not in Locked state
     */
    function refundEscrow(bytes32 tradeId)
        external
        onlyAuthorized
        validEscrow(tradeId)
        canRefund(tradeId)
        nonReentrant
        returns (bool)
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);
        
        // Ensure escrow is still in Locked status
        if (escrow.status != EscrowTypes.EscrowStatus.Locked) {
            revert EscrowTypes.InvalidStatus();
        }
        
        // MATH: Fee calculation - (amount * 25) / 10000 = 0.25%
        // Example: 100 USDT * 25 / 10000 = 0.25 USDT fee
        uint256 feeAmount = (escrow.amount * REFUND_FEE_BPS) / 10000;
        uint256 sellerAmount = escrow.amount - feeAmount;
        
        // Transfer fee to feeRecipient
        if (feeAmount > 0 && feeRecipient != address(0)) {
            IERC20(escrow.token).safeTransfer(feeRecipient, feeAmount);
            emit EscrowTypes.FeeCollected(tradeId, escrow.token, feeRecipient, feeAmount, block.timestamp);
        }
        
        // Transfer remaining to seller
        IERC20(escrow.token).safeTransfer(escrow.seller, sellerAmount);
        
        // Update status
        _updateEscrowStatus(tradeId, EscrowTypes.EscrowStatus.Refunded);
        
        emit EscrowTypes.EscrowRefunded(tradeId, escrow.seller, sellerAmount, block.timestamp);
        return true;
    }

    /**
     * @notice Force release escrow to buyer by admin (dispute resolution)
     * @dev FINANCIAL: Deducts 0.75% platform fee before transfer
     *      MATH: feeAmount = (amount * FEE_BPS) / 10000, buyerAmount = amount - feeAmount
     *      ACCESS: Only callable by authorized signers (admin)
     *      REENTRANCY: Protected by nonReentrant modifier
     *      SECURITY: Used when backend dispute resolution favors buyer
     * @param tradeId Trade identifier
     * @return bool Always returns true on success
     * @custom:throws EscrowTypes.InvalidStatus if escrow not in Locked state
     * @custom:throws EscrowTypes.Unauthorized if caller not authorized
     */
    function forceReleaseEscrow(bytes32 tradeId)
        external
        onlyAuthorized
        validEscrow(tradeId)
        nonReentrant
        returns (bool)
    {
        EscrowTypes.Escrow storage escrow = _getEscrow(tradeId);

        // Allow force release only if Locked
        if (escrow.status != EscrowTypes.EscrowStatus.Locked) {
            revert EscrowTypes.InvalidStatus();
        }

        // MATH: Fee calculation - (amount * 75) / 10000 = 0.75%
        // Example: 100 USDT * 75 / 10000 = 0.75 USDT fee
        uint256 feeAmount = (escrow.amount * FEE_BPS) / 10000;
        uint256 buyerAmount = escrow.amount - feeAmount;

        // Transfer fee to feeRecipient
        if (feeAmount > 0 && feeRecipient != address(0)) {
            IERC20(escrow.token).safeTransfer(feeRecipient, feeAmount);
            emit EscrowTypes.FeeCollected(tradeId, escrow.token, feeRecipient, feeAmount, block.timestamp);
        }

        // Transfer remaining to buyer
        IERC20(escrow.token).safeTransfer(escrow.buyer, buyerAmount);

        // Update status
        _updateEscrowStatus(tradeId, EscrowTypes.EscrowStatus.Released);

        emit EscrowTypes.EscrowForceReleased(tradeId, escrow.buyer, buyerAmount, msg.sender, block.timestamp);
        return true;
    }
}